export { default as App } from './App/app'
export { default as Button } from './button/button'
export { default as Card } from './card/card'
export { default as Game } from './Game/Game'
export { default as Status } from './Status/Status'
export { default as Text } from './text/text'
